service: game-parser
# app and org for use with dashboard.serverless.com
#app: your-app-name
#org: your-org-name

provider:
  name: aws
  runtime: nodejs10.x
  memorySize: 512
  timeout: 30

  region: eu-central-1

  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - dynamodb:PutItem
      Resource:
        Fn::Join:
          - ':'
          - - arn
            - aws
            - dynamodb
            - Ref: AWS::Region
            - Ref: AWS::AccountId
            - table/${file(../config.json):game-table-name}

  environment:
    TABLE_NAME: ${file(../config.json):game-table-name}

functions:
  game-parser:
    handler: handler.parseGame
    events:
      - sqs:
          arn:
            Fn::Join:
              - ':'
              - - arn
                - aws
                - sqs
                - Ref: AWS::Region
                - Ref: AWS::AccountId
                - ${file(../config.json):game-parse-queue-name}
          batchSize: 1
