service: league-parser-trigger
# app and org for use with dashboard.serverless.com
#app: your-app-name
#org: your-org-name

provider:
  name: aws
  runtime: nodejs10.x
  memorySize: 256
  timeout: 20

  region: eu-central-1

  iamRoleStatements:
   - Effect: "Allow"
     Action:
       - "sqs:SendMessage"
     Resource:
       Fn::Join:
         - ':'
         - - arn
           - aws
           - sqs
           - Ref: AWS::Region
           - Ref: AWS::AccountId
           - ${file(../config.json):league-parse-queue-name}

  environment:
    QUEUE_NAME: ${file(../config.json):league-parse-queue-name}

functions:
  league-parser-trigger:
    handler: handler.triggerParseLeagues
    events:
      - schedule: cron(30 23 * * ? *)

package:
  include:
    - ../imports/leagues.json
    - ../imports/trigger.js
