import { Association, RawAssociation } from '@h-hub/models';
import { Resolver } from "./resolver";
import { transformRawAssociation } from './transformer';

const ASSOCIATION = {
    "header": {
        "version": "alpha",
        "(C)": "Handball4all AG"
    },
    "menu": {
        "org": {
            "list": {
                "4": "Handball Baden-Württemberg",
                "35": "Badischer Handball-Verband",
                "36": "Bruchsal",
                "37": "Heidelberg"
            },
            "selectedID": "35"
        },
        "period": {
            "list": {
                "48": "14/15",
                "50": "15/16",
                "51": "S 2016",
                "52": "16/17",
                "54": "S 2017",
                "58": "17/18",
                "62": "S 2018",
                "68": "18/19",
                "75": "S 2019",
                "83": "19/20",
                "91": "20/21"
            },
            "selectedID": "91"
        },
        "dt": {
            "list": {
                "2020-09-14": "14.09.2020",
                "2020-09-21": "21.09.2020",
                "2020-09-28": "28.09.2020",
                "2020-10-05": "05.10.2020",
                "2020-10-12": "12.10.2020",
                "2020-10-19": "19.10.2020",
                "2020-10-26": "26.10.2020",
                "2020-11-02": "02.11.2020",
                "2020-11-09": "09.11.2020",
                "2020-11-16": "16.11.2020",
                "2020-11-23": "23.11.2020",
                "2020-11-30": "30.11.2020",
                "2020-12-07": "07.12.2020",
                "2020-12-14": "14.12.2020",
                "2021-01-04": "04.01.2021",
                "2021-01-11": "11.01.2021",
                "2021-01-18": "18.01.2021",
                "2021-01-25": "25.01.2021",
                "2021-02-01": "01.02.2021",
                "2021-02-08": "08.02.2021",
                "2021-02-15": "15.02.2021",
                "2021-02-22": "22.02.2021",
                "2021-03-01": "01.03.2021",
                "2021-03-08": "08.03.2021",
                "2021-03-15": "15.03.2021",
                "2021-03-22": "22.03.2021",
                "2021-04-05": "05.04.2021",
                "2021-04-12": "12.04.2021",
                "2021-04-19": "19.04.2021",
                "2021-05-03": "03.05.2021",
                "2021-05-10": "10.05.2021"
            },
            "selected": "2020-11-30"
        }
    },
    "head": {
        "name": "Badischer Handball-Verband",
        "sname": "BHV",
        "headline1": "Wochenübersicht vom 30.11.2020 - 06.12.2020",
        "headline2": "Badischer Handball-Verband - Hallenrunde 2020/2021",
        "actualized": "Letzte Änderung: Do, 08.10.2020, 15:00h",
        "live": 0,
        "repURL": "http://spo.handball4all.de/misc/sboPublicReports.php?sGID="
    },
    "content": {
        "classes": [
            {
                "gClassID": "57411",
                "gClassSname": "M-BL",
                "gClassLname": "Badenliga Männer",
                "gClassGender": "m",
                "gClassAGsDesc": "M",
                "gClassAGsYear": "18",
                "gRefAllocType": "org_assigned",
                "gRefRespOrg": "35",
                "games": [
                    {
                        "gID": "3918491",
                        "sGID": 0,
                        "gNo": "210010",
                        "live": false,
                        "gToken": "",
                        "gAppid": "",
                        "gDate": "01.12.20",
                        "gWDay": "Di",
                        "gTime": "20:00",
                        "gGymnasiumID": "911",
                        "gGymnasiumNo": "23015",
                        "gGymnasiumName": "Sporthalle 1 Schulzentrum Blankenloch",
                        "gGymnasiumPostal": "76297",
                        "gGymnasiumTown": "Stutensee-Blankenloch",
                        "gGymnasiumStreet": "Gymnasiumstraße 20",
                        "gHomeTeam": "SG Stuten-Wein",
                        "gGuestTeam": "TV Knielingen",
                        "gHomeGoals": " ",
                        "gGuestGoals": " ",
                        "gHomeGoals_1": " ",
                        "gGuestGoals_1": " ",
                        "gHomePoints": " ",
                        "gGuestPoints": " ",
                        "gComment": "abgesetzt",
                        "gGroupsortTxt": " ",
                        "gReferee": " "
                    },
                    {
                        "gID": "3918871",
                        "sGID": 0,
                        "gNo": "210086",
                        "live": false,
                        "gToken": "",
                        "gAppid": "",
                        "gDate": "05.12.20",
                        "gWDay": "Sa",
                        "gTime": "19:00",
                        "gGymnasiumID": "646",
                        "gGymnasiumNo": "22002",
                        "gGymnasiumName": "Stadionhalle",
                        "gGymnasiumPostal": "69168",
                        "gGymnasiumTown": "Wiesloch",
                        "gGymnasiumStreet": "Parkstraße 5",
                        "gHomeTeam": "TSG Wiesloch",
                        "gGuestTeam": "SG Leutersh. 2",
                        "gHomeGoals": " ",
                        "gGuestGoals": " ",
                        "gHomeGoals_1": " ",
                        "gGuestGoals_1": " ",
                        "gHomePoints": " ",
                        "gGuestPoints": " ",
                        "gComment": " ",
                        "gGroupsortTxt": " ",
                        "gReferee": " "
                    },
                    {
                        "gID": "3918861",
                        "sGID": 0,
                        "gNo": "210084",
                        "live": false,
                        "gToken": "",
                        "gAppid": "",
                        "gDate": "05.12.20",
                        "gWDay": "Sa",
                        "gTime": "19:00",
                        "gGymnasiumID": "609",
                        "gGymnasiumNo": "24012",
                        "gGymnasiumName": "Jahnhalle",
                        "gGymnasiumPostal": "68766",
                        "gGymnasiumTown": "Hockenheim",
                        "gGymnasiumStreet": "Waldstraße 1",
                        "gHomeTeam": "HSV Hockenheim",
                        "gGuestTeam": "TSG Plankstadt",
                        "gHomeGoals": " ",
                        "gGuestGoals": " ",
                        "gHomeGoals_1": " ",
                        "gGuestGoals_1": " ",
                        "gHomePoints": " ",
                        "gGuestPoints": " ",
                        "gComment": " ",
                        "gGroupsortTxt": " ",
                        "gReferee": " "
                    },
                    {
                        "gID": "3918851",
                        "sGID": 0,
                        "gNo": "210082",
                        "live": false,
                        "gToken": "",
                        "gAppid": "",
                        "gDate": "05.12.20",
                        "gWDay": "Sa",
                        "gTime": "19:30",
                        "gGymnasiumID": "960",
                        "gGymnasiumNo": "24044",
                        "gGymnasiumName": "Waldsporthalle",
                        "gGymnasiumPostal": "68519",
                        "gGymnasiumTown": "Viernheim",
                        "gGymnasiumStreet": "Industriestraße 38",
                        "gHomeTeam": "TSV A Viernh'm",
                        "gGuestTeam": "TSV Rot",
                        "gHomeGoals": " ",
                        "gGuestGoals": " ",
                        "gHomeGoals_1": " ",
                        "gGuestGoals_1": " ",
                        "gHomePoints": " ",
                        "gGuestPoints": " ",
                        "gComment": " ",
                        "gGroupsortTxt": " ",
                        "gReferee": " "
                    },
                    {
                        "gID": "3918866",
                        "sGID": 0,
                        "gNo": "210085",
                        "live": false,
                        "gToken": "",
                        "gAppid": "",
                        "gDate": "05.12.20",
                        "gWDay": "Sa",
                        "gTime": "19:30",
                        "gGymnasiumID": "47",
                        "gGymnasiumNo": "26002",
                        "gGymnasiumName": "Walter-Hohmann-Schulsporthalle",
                        "gGymnasiumPostal": "74736",
                        "gGymnasiumTown": "Hardheim",
                        "gGymnasiumStreet": "Bürgermeister-Henn-Straße",
                        "gHomeTeam": "TV Hardheim",
                        "gGuestTeam": "HG Ofter/Schw 2",
                        "gHomeGoals": " ",
                        "gGuestGoals": " ",
                        "gHomeGoals_1": " ",
                        "gGuestGoals_1": " ",
                        "gHomePoints": " ",
                        "gGuestPoints": " ",
                        "gComment": " ",
                        "gGroupsortTxt": " ",
                        "gReferee": " "
                    },
                    {
                        "gID": "3918856",
                        "sGID": 0,
                        "gNo": "210083",
                        "live": false,
                        "gToken": "",
                        "gAppid": "",
                        "gDate": "05.12.20",
                        "gWDay": "Sa",
                        "gTime": "20:00",
                        "gGymnasiumID": "496",
                        "gGymnasiumNo": "25008",
                        "gGymnasiumName": "Konrad-Adenauer-Sporthalle",
                        "gGymnasiumPostal": "75181",
                        "gGymnasiumTown": "Pforzheim",
                        "gGymnasiumStreet": "Kaulbachstraße 32",
                        "gHomeTeam": "SG PF/Eutingen 2",
                        "gGuestTeam": "TV Friedrichsf",
                        "gHomeGoals": " ",
                        "gGuestGoals": " ",
                        "gHomeGoals_1": " ",
                        "gGuestGoals_1": " ",
                        "gHomePoints": " ",
                        "gGuestPoints": " ",
                        "gComment": " ",
                        "gGroupsortTxt": " ",
                        "gReferee": " "
                    },
                    {
                        "gID": "3918876",
                        "sGID": 0,
                        "gNo": "210087",
                        "live": false,
                        "gToken": "",
                        "gAppid": "",
                        "gDate": "06.12.20",
                        "gWDay": "So",
                        "gTime": "17:30",
                        "gGymnasiumID": "901",
                        "gGymnasiumNo": "23005",
                        "gGymnasiumName": "Reinhold-Crocoll Sporthalle",
                        "gGymnasiumPostal": "76187",
                        "gGymnasiumTown": "Karlsruhe-Knielingen",
                        "gGymnasiumStreet": "Am Brurain 4-6",
                        "gHomeTeam": "TV Knielingen",
                        "gGuestTeam": "TV Eppelheim",
                        "gHomeGoals": " ",
                        "gGuestGoals": " ",
                        "gHomeGoals_1": " ",
                        "gGuestGoals_1": " ",
                        "gHomePoints": " ",
                        "gGuestPoints": " ",
                        "gComment": " ",
                        "gGroupsortTxt": " ",
                        "gReferee": " "
                    },
                    {
                        "gID": "3918846",
                        "sGID": 0,
                        "gNo": "210081",
                        "live": false,
                        "gToken": "",
                        "gAppid": "",
                        "gDate": "06.12.20",
                        "gWDay": "So",
                        "gTime": "17:30",
                        "gGymnasiumID": "493",
                        "gGymnasiumNo": "24007",
                        "gGymnasiumName": "Nordbadenhalle 1",
                        "gGymnasiumPostal": "68542",
                        "gGymnasiumTown": "Heddesheim",
                        "gGymnasiumStreet": "Ahornstraße 72",
                        "gHomeTeam": "SG Heddesheim",
                        "gGuestTeam": "SG Heidel/Helm",
                        "gHomeGoals": " ",
                        "gGuestGoals": " ",
                        "gHomeGoals_1": " ",
                        "gGuestGoals_1": " ",
                        "gHomePoints": " ",
                        "gGuestPoints": " ",
                        "gComment": " ",
                        "gGroupsortTxt": " ",
                        "gReferee": " "
                    },
                    {
                        "gID": "3918881",
                        "sGID": 0,
                        "gNo": "210088",
                        "live": false,
                        "gToken": "",
                        "gAppid": "",
                        "gDate": "06.12.20",
                        "gWDay": "So",
                        "gTime": "18:00",
                        "gGymnasiumID": "911",
                        "gGymnasiumNo": "23015",
                        "gGymnasiumName": "Sporthalle 1 Schulzentrum Blankenloch",
                        "gGymnasiumPostal": "76297",
                        "gGymnasiumTown": "Stutensee-Blankenloch",
                        "gGymnasiumStreet": "Gymnasiumstraße 20",
                        "gHomeTeam": "SG Stuten-Wein",
                        "gGuestTeam": "HSG St.Le/Reil",
                        "gHomeGoals": " ",
                        "gGuestGoals": " ",
                        "gHomeGoals_1": " ",
                        "gGuestGoals_1": " ",
                        "gHomePoints": " ",
                        "gGuestPoints": " ",
                        "gComment": " ",
                        "gGroupsortTxt": " ",
                        "gReferee": " "
                    }
                ]
            },
            {
                "gClassID": "57431",
                "gClassSname": "M-VL",
                "gClassLname": "Verbandsliga Männer",
                "gClassGender": "m",
                "gClassAGsDesc": "M",
                "gClassAGsYear": "18",
                "gRefAllocType": "org_assigned",
                "gRefRespOrg": "35",
                "games": [
                    {
                        "gID": "3924526",
                        "sGID": 0,
                        "gNo": "210324",
                        "live": false,
                        "gToken": "",
                        "gAppid": "",
                        "gDate": "05.12.20",
                        "gWDay": "Sa",
                        "gTime": "18:00",
                        "gGymnasiumID": "913",
                        "gGymnasiumNo": "23017",
                        "gGymnasiumName": "Sportzentrum Eggenstein 1",
                        "gGymnasiumPostal": "76344",
                        "gGymnasiumTown": "Eggenstein-Leopoldshafen",
                        "gGymnasiumStreet": "Buchheimer Weg 6",
                        "gHomeTeam": "TG Eggenstein",
                        "gGuestTeam": "TSV Rintheim",
                        "gHomeGoals": " ",
                        "gGuestGoals": " ",
                        "gHomeGoals_1": " ",
                        "gGuestGoals_1": " ",
                        "gHomePoints": " ",
                        "gGuestPoints": " ",
                        "gComment": " ",
                        "gGroupsortTxt": " ",
                        "gReferee": " "
                    },
                    {
                        "gID": "3924506",
                        "sGID": 0,
                        "gNo": "210320",
                        "live": false,
                        "gToken": "",
                        "gAppid": "",
                        "gDate": "05.12.20",
                        "gWDay": "Sa",
                        "gTime": "19:45",
                        "gGymnasiumID": "487",
                        "gGymnasiumNo": "22010",
                        "gGymnasiumName": "Rebland-Halle",
                        "gGymnasiumPostal": "69254",
                        "gGymnasiumTown": "Malsch",
                        "gGymnasiumStreet": "Unterer Jagdweg 69",
                        "gHomeTeam": "TSVG Malsch",
                        "gGuestTeam": "TGS Pforzheim 2",
                        "gHomeGoals": " ",
                        "gGuestGoals": " ",
                        "gHomeGoals_1": " ",
                        "gGuestGoals_1": " ",
                        "gHomePoints": " ",
                        "gGuestPoints": " ",
                        "gComment": " ",
                        "gGroupsortTxt": " ",
                        "gReferee": " "
                    },
                    {
                        "gID": "3924536",
                        "sGID": 0,
                        "gNo": "210326",
                        "live": false,
                        "gToken": "",
                        "gAppid": "",
                        "gDate": "05.12.20",
                        "gWDay": "Sa",
                        "gTime": "20:00",
                        "gGymnasiumID": "869",
                        "gGymnasiumNo": "22008",
                        "gGymnasiumName": "Sportzentrum Nord 1",
                        "gGymnasiumPostal": "69120",
                        "gGymnasiumTown": "Heidelberg",
                        "gGymnasiumStreet": "Tiergartenstraße 126",
                        "gHomeTeam": "TSV H'schuhsh",
                        "gGuestTeam": "HSG Dittig/TBB",
                        "gHomeGoals": " ",
                        "gGuestGoals": " ",
                        "gHomeGoals_1": " ",
                        "gGuestGoals_1": " ",
                        "gHomePoints": " ",
                        "gGuestPoints": " ",
                        "gComment": " ",
                        "gGroupsortTxt": " ",
                        "gReferee": " "
                    },
                    {
                        "gID": "3924511",
                        "sGID": 0,
                        "gNo": "210321",
                        "live": false,
                        "gToken": "",
                        "gAppid": "",
                        "gDate": "05.12.20",
                        "gWDay": "Sa",
                        "gTime": "20:00",
                        "gGymnasiumID": "933",
                        "gGymnasiumNo": "23039",
                        "gGymnasiumName": "Sporthalle",
                        "gGymnasiumPostal": "75045",
                        "gGymnasiumTown": "Walzbachtal-Wössingen",
                        "gGymnasiumStreet": "Wössinger Straße 123",
                        "gHomeTeam": "HSG Walzbacht.",
                        "gGuestTeam": "HSG Ettlingen",
                        "gHomeGoals": " ",
                        "gGuestGoals": " ",
                        "gHomeGoals_1": " ",
                        "gGuestGoals_1": " ",
                        "gHomePoints": " ",
                        "gGuestPoints": " ",
                        "gComment": " ",
                        "gGroupsortTxt": " ",
                        "gReferee": " "
                    },
                    {
                        "gID": "3924531",
                        "sGID": 0,
                        "gNo": "210325",
                        "live": false,
                        "gToken": "",
                        "gAppid": "",
                        "gDate": "06.12.20",
                        "gWDay": "So",
                        "gTime": "17:00",
                        "gGymnasiumID": "888",
                        "gGymnasiumNo": "22033",
                        "gGymnasiumName": "Sportzentrum West",
                        "gGymnasiumPostal": "69123",
                        "gGymnasiumTown": "Heidelberg",
                        "gGymnasiumStreet": "Hinterer Entenpfuhl 10",
                        "gHomeTeam": "TSV Wieblingen",
                        "gGuestTeam": "SG Oden/U'öwi",
                        "gHomeGoals": " ",
                        "gGuestGoals": " ",
                        "gHomeGoals_1": " ",
                        "gGuestGoals_1": " ",
                        "gHomePoints": " ",
                        "gGuestPoints": " ",
                        "gComment": " ",
                        "gGroupsortTxt": " ",
                        "gReferee": " "
                    },
                    {
                        "gID": "3924516",
                        "sGID": 0,
                        "gNo": "210322",
                        "live": false,
                        "gToken": "",
                        "gAppid": "",
                        "gDate": "06.12.20",
                        "gWDay": "So",
                        "gTime": "17:00",
                        "gGymnasiumID": "974",
                        "gGymnasiumNo": "25013",
                        "gGymnasiumName": "Schulsporthalle",
                        "gGymnasiumPostal": "75228",
                        "gGymnasiumTown": "Ispringen",
                        "gGymnasiumStreet": "Turnstraße 50",
                        "gHomeTeam": "TV Ispringen",
                        "gGuestTeam": "TV Mosbach",
                        "gHomeGoals": " ",
                        "gGuestGoals": " ",
                        "gHomeGoals_1": " ",
                        "gGuestGoals_1": " ",
                        "gHomePoints": " ",
                        "gGuestPoints": " ",
                        "gComment": " ",
                        "gGroupsortTxt": " ",
                        "gReferee": " "
                    },
                    {
                        "gID": "3924521",
                        "sGID": 0,
                        "gNo": "210323",
                        "live": false,
                        "gToken": "",
                        "gAppid": "",
                        "gDate": "06.12.20",
                        "gWDay": "So",
                        "gTime": "18:00",
                        "gGymnasiumID": "879",
                        "gGymnasiumNo": "22023",
                        "gGymnasiumName": "Jahnhalle",
                        "gGymnasiumPostal": "69221",
                        "gGymnasiumTown": "Dossenheim",
                        "gGymnasiumStreet": "Gerhart-Hauptmann-Straße 16",
                        "gHomeTeam": "TSG Dossenheim",
                        "gGuestTeam": "TVG Großsachs 2",
                        "gHomeGoals": " ",
                        "gGuestGoals": " ",
                        "gHomeGoals_1": " ",
                        "gGuestGoals_1": " ",
                        "gHomePoints": " ",
                        "gGuestPoints": " ",
                        "gComment": " ",
                        "gGroupsortTxt": " ",
                        "gReferee": " "
                    }
                ]
            },
            {
                "gClassID": "57436",
                "gClassSname": "F-BL",
                "gClassLname": "Badenliga Frauen",
                "gClassGender": "w",
                "gClassAGsDesc": "F",
                "gClassAGsYear": "18",
                "gRefAllocType": "org_assigned",
                "gRefRespOrg": "35",
                "games": [
                    {
                        "gID": "3921726",
                        "sGID": 0,
                        "gNo": "210553",
                        "live": false,
                        "gToken": "",
                        "gAppid": "",
                        "gDate": "05.12.20",
                        "gWDay": "Sa",
                        "gTime": "17:00",
                        "gGymnasiumID": "646",
                        "gGymnasiumNo": "22002",
                        "gGymnasiumName": "Stadionhalle",
                        "gGymnasiumPostal": "69168",
                        "gGymnasiumTown": "Wiesloch",
                        "gGymnasiumStreet": "Parkstraße 5",
                        "gHomeTeam": "TSG Wiesloch",
                        "gGuestTeam": "HG Saase",
                        "gHomeGoals": " ",
                        "gGuestGoals": " ",
                        "gHomeGoals_1": " ",
                        "gGuestGoals_1": " ",
                        "gHomePoints": " ",
                        "gGuestPoints": " ",
                        "gComment": " ",
                        "gGroupsortTxt": " ",
                        "gReferee": " "
                    },
                    {
                        "gID": "3921716",
                        "sGID": 0,
                        "gNo": "210551",
                        "live": false,
                        "gToken": "",
                        "gAppid": "",
                        "gDate": "05.12.20",
                        "gWDay": "Sa",
                        "gTime": "17:15",
                        "gGymnasiumID": "960",
                        "gGymnasiumNo": "24044",
                        "gGymnasiumName": "Waldsporthalle",
                        "gGymnasiumPostal": "68519",
                        "gGymnasiumTown": "Viernheim",
                        "gGymnasiumStreet": "Industriestraße 38",
                        "gHomeTeam": "TSV A Viernh'm",
                        "gGuestTeam": "SG Nußloch",
                        "gHomeGoals": " ",
                        "gGuestGoals": " ",
                        "gHomeGoals_1": " ",
                        "gGuestGoals_1": " ",
                        "gHomePoints": " ",
                        "gGuestPoints": " ",
                        "gComment": " ",
                        "gGroupsortTxt": " ",
                        "gReferee": " "
                    },
                    {
                        "gID": "3921736",
                        "sGID": 0,
                        "gNo": "210555",
                        "live": false,
                        "gToken": "",
                        "gAppid": "",
                        "gDate": "06.12.20",
                        "gWDay": "So",
                        "gTime": "15:30",
                        "gGymnasiumID": "868",
                        "gGymnasiumNo": "22007",
                        "gGymnasiumName": "Leimbachhalle",
                        "gGymnasiumPostal": "69234",
                        "gGymnasiumTown": "Dielheim",
                        "gGymnasiumStreet": "Pestalozzistraße 14",
                        "gHomeTeam": "TV Dielheim",
                        "gGuestTeam": "SG Stuten-Wein",
                        "gHomeGoals": " ",
                        "gGuestGoals": " ",
                        "gHomeGoals_1": " ",
                        "gGuestGoals_1": " ",
                        "gHomePoints": " ",
                        "gGuestPoints": " ",
                        "gComment": " ",
                        "gGroupsortTxt": " ",
                        "gReferee": " "
                    },
                    {
                        "gID": "3921721",
                        "sGID": 0,
                        "gNo": "210552",
                        "live": false,
                        "gToken": "",
                        "gAppid": "",
                        "gDate": "06.12.20",
                        "gWDay": "So",
                        "gTime": "15:30",
                        "gGymnasiumID": "493",
                        "gGymnasiumNo": "24007",
                        "gGymnasiumName": "Nordbadenhalle 1",
                        "gGymnasiumPostal": "68542",
                        "gGymnasiumTown": "Heddesheim",
                        "gGymnasiumStreet": "Ahornstraße 72",
                        "gHomeTeam": "SG Heddesheim",
                        "gGuestTeam": "TSV Rot",
                        "gHomeGoals": " ",
                        "gGuestGoals": " ",
                        "gHomeGoals_1": " ",
                        "gGuestGoals_1": " ",
                        "gHomePoints": " ",
                        "gGuestPoints": " ",
                        "gComment": " ",
                        "gGroupsortTxt": " ",
                        "gReferee": " "
                    },
                    {
                        "gID": "3921731",
                        "sGID": 0,
                        "gNo": "210554",
                        "live": false,
                        "gToken": "",
                        "gAppid": "",
                        "gDate": "06.12.20",
                        "gWDay": "So",
                        "gTime": "15:30",
                        "gGymnasiumID": "58",
                        "gGymnasiumNo": "26003",
                        "gGymnasiumName": "Tauber-Franken-Sporthalle",
                        "gGymnasiumPostal": "97922",
                        "gGymnasiumTown": "Lauda-Königshofen",
                        "gGymnasiumStreet": "Hauptstraße",
                        "gHomeTeam": "HG Kön/Sachs",
                        "gGuestTeam": "TSV Rintheim",
                        "gHomeGoals": " ",
                        "gGuestGoals": " ",
                        "gHomeGoals_1": " ",
                        "gGuestGoals_1": " ",
                        "gHomePoints": " ",
                        "gGuestPoints": " ",
                        "gComment": " ",
                        "gGroupsortTxt": " ",
                        "gReferee": " "
                    }
                ]
            },
            {
                "gClassID": "57441",
                "gClassSname": "F-VL",
                "gClassLname": "Verbandsliga Frauen",
                "gClassGender": "w",
                "gClassAGsDesc": "F",
                "gClassAGsYear": "18",
                "gRefAllocType": "org_assigned",
                "gRefRespOrg": "35",
                "games": [
                    {
                        "gID": "3922491",
                        "sGID": 0,
                        "gNo": "211774",
                        "live": false,
                        "gToken": "",
                        "gAppid": "",
                        "gDate": "05.12.20",
                        "gWDay": "Sa",
                        "gTime": "17:00",
                        "gGymnasiumID": "956",
                        "gGymnasiumNo": "24038",
                        "gGymnasiumName": "Schulzentrum",
                        "gGymnasiumPostal": "69198",
                        "gGymnasiumTown": "Schriesheim",
                        "gGymnasiumStreet": "Hirschberger Straße",
                        "gHomeTeam": "TV Schriesheim",
                        "gGuestTeam": "SG Walld Ast F",
                        "gHomeGoals": " ",
                        "gGuestGoals": " ",
                        "gHomeGoals_1": " ",
                        "gGuestGoals_1": " ",
                        "gHomePoints": " ",
                        "gGuestPoints": " ",
                        "gComment": " ",
                        "gGroupsortTxt": " ",
                        "gReferee": " "
                    },
                    {
                        "gID": "3922486",
                        "sGID": 0,
                        "gNo": "211773",
                        "live": false,
                        "gToken": "",
                        "gAppid": "",
                        "gDate": "05.12.20",
                        "gWDay": "Sa",
                        "gTime": "17:30",
                        "gGymnasiumID": "487",
                        "gGymnasiumNo": "22010",
                        "gGymnasiumName": "Rebland-Halle",
                        "gGymnasiumPostal": "69254",
                        "gGymnasiumTown": "Malsch",
                        "gGymnasiumStreet": "Unterer Jagdweg 69",
                        "gHomeTeam": "TSVG Malsch",
                        "gGuestTeam": "HSG St.Le/Reil 2",
                        "gHomeGoals": " ",
                        "gGuestGoals": " ",
                        "gHomeGoals_1": " ",
                        "gGuestGoals_1": " ",
                        "gHomePoints": " ",
                        "gGuestPoints": " ",
                        "gComment": " ",
                        "gGroupsortTxt": " ",
                        "gReferee": " "
                    },
                    {
                        "gID": "3922496",
                        "sGID": 0,
                        "gNo": "211775",
                        "live": false,
                        "gToken": "",
                        "gAppid": "",
                        "gDate": "05.12.20",
                        "gWDay": "Sa",
                        "gTime": "17:30",
                        "gGymnasiumID": "871",
                        "gGymnasiumNo": "22013",
                        "gGymnasiumName": "Sportparkhalle",
                        "gGymnasiumPostal": "69181",
                        "gGymnasiumTown": "Leimen",
                        "gGymnasiumStreet": "Peter-Disegna-Weg ",
                        "gHomeTeam": "KuSG Leimen",
                        "gGuestTeam": "TSV Birkenau 2",
                        "gHomeGoals": " ",
                        "gGuestGoals": " ",
                        "gHomeGoals_1": " ",
                        "gGuestGoals_1": " ",
                        "gHomePoints": " ",
                        "gGuestPoints": " ",
                        "gComment": " ",
                        "gGroupsortTxt": " ",
                        "gReferee": " "
                    },
                    {
                        "gID": "3922501",
                        "sGID": 0,
                        "gNo": "211776",
                        "live": false,
                        "gToken": "",
                        "gAppid": "",
                        "gDate": "05.12.20",
                        "gWDay": "Sa",
                        "gTime": "18:00",
                        "gGymnasiumID": "938",
                        "gGymnasiumNo": "24013",
                        "gGymnasiumName": "Neckarhalle",
                        "gGymnasiumPostal": "68549",
                        "gGymnasiumTown": "Ilvesheim",
                        "gGymnasiumStreet": "Heddesheimer Straße",
                        "gHomeTeam": "Spvgg Ilvesh.",
                        "gGuestTeam": "R-N Löwen",
                        "gHomeGoals": " ",
                        "gGuestGoals": " ",
                        "gHomeGoals_1": " ",
                        "gGuestGoals_1": " ",
                        "gHomePoints": " ",
                        "gGuestPoints": " ",
                        "gComment": " ",
                        "gGroupsortTxt": " ",
                        "gReferee": " "
                    },
                    {
                        "gID": "3922506",
                        "sGID": 0,
                        "gNo": "211777",
                        "live": false,
                        "gToken": "",
                        "gAppid": "",
                        "gDate": "05.12.20",
                        "gWDay": "Sa",
                        "gTime": "18:00",
                        "gGymnasiumID": "947",
                        "gGymnasiumNo": "24026",
                        "gGymnasiumName": "Sporthalle, Vogelstang Geschw.Scholl Sch.",
                        "gGymnasiumPostal": "68309",
                        "gGymnasiumTown": "Mannheim",
                        "gGymnasiumStreet": "Pommernstraße 106",
                        "gHomeTeam": "HC MA-Vogelst.",
                        "gGuestTeam": "TS Mühlburg",
                        "gHomeGoals": " ",
                        "gGuestGoals": " ",
                        "gHomeGoals_1": " ",
                        "gGuestGoals_1": " ",
                        "gHomePoints": " ",
                        "gGuestPoints": " ",
                        "gComment": " ",
                        "gGroupsortTxt": " ",
                        "gReferee": " "
                    },
                    {
                        "gID": "3922476",
                        "sGID": 0,
                        "gNo": "211771",
                        "live": false,
                        "gToken": "",
                        "gAppid": "",
                        "gDate": "06.12.20",
                        "gWDay": "So",
                        "gTime": "15:00",
                        "gGymnasiumID": "488",
                        "gGymnasiumNo": "25006",
                        "gGymnasiumName": "Sporthalle beim Fritz-Erler-Gymnasium",
                        "gGymnasiumPostal": "75172",
                        "gGymnasiumTown": "Pforzheim",
                        "gGymnasiumStreet": "Westliche Karl-Friedrich-Straße 215",
                        "gHomeTeam": "TG Pforzheim 2",
                        "gGuestTeam": "SG Heidel/Helm 2",
                        "gHomeGoals": " ",
                        "gGuestGoals": " ",
                        "gHomeGoals_1": " ",
                        "gGuestGoals_1": " ",
                        "gHomePoints": " ",
                        "gGuestPoints": " ",
                        "gComment": " ",
                        "gGroupsortTxt": " ",
                        "gReferee": " "
                    },
                    {
                        "gID": "3922481",
                        "sGID": 0,
                        "gNo": "211772",
                        "live": false,
                        "gToken": "",
                        "gAppid": "",
                        "gDate": "06.12.20",
                        "gWDay": "So",
                        "gTime": "18:00",
                        "gGymnasiumID": "912",
                        "gGymnasiumNo": "23016",
                        "gGymnasiumName": "Franz-Kühn Halle",
                        "gGymnasiumPostal": "76275",
                        "gGymnasiumTown": "Ettlingen-Bruchhausen",
                        "gGymnasiumStreet": "Teichweg 2",
                        "gHomeTeam": "HSG Ettlingen",
                        "gGuestTeam": "TG Neureut",
                        "gHomeGoals": " ",
                        "gGuestGoals": " ",
                        "gHomeGoals_1": " ",
                        "gGuestGoals_1": " ",
                        "gHomePoints": " ",
                        "gGuestPoints": " ",
                        "gComment": " ",
                        "gGroupsortTxt": " ",
                        "gReferee": " "
                    }
                ]
            },
            {
                "gClassID": "57821",
                "gClassSname": "mJA-BL",
                "gClassLname": "Badenliga männl. A",
                "gClassGender": "m",
                "gClassAGsDesc": "A",
                "gClassAGsYear": "17",
                "gRefAllocType": "org_assigned",
                "gRefRespOrg": "35",
                "games": [
                    {
                        "gID": "3979076",
                        "sGID": 0,
                        "gNo": "213043",
                        "live": false,
                        "gToken": "",
                        "gAppid": "",
                        "gDate": "05.12.20",
                        "gWDay": "Sa",
                        "gTime": "18:30",
                        "gGymnasiumID": "597",
                        "gGymnasiumNo": "24005",
                        "gGymnasiumName": "Großsporthalle",
                        "gGymnasiumPostal": "68535",
                        "gGymnasiumTown": "Edingen-Neckarhausen",
                        "gGymnasiumStreet": "Robert-Walter-Straße 1",
                        "gHomeTeam": "SG Eding/Fried",
                        "gGuestTeam": "SG Nußloch",
                        "gHomeGoals": " ",
                        "gGuestGoals": " ",
                        "gHomeGoals_1": " ",
                        "gGuestGoals_1": " ",
                        "gHomePoints": " ",
                        "gGuestPoints": " ",
                        "gComment": " ",
                        "gGroupsortTxt": " ",
                        "gReferee": " "
                    },
                    {
                        "gID": "3979081",
                        "sGID": 0,
                        "gNo": "213044",
                        "live": false,
                        "gToken": "",
                        "gAppid": "",
                        "gDate": "06.12.20",
                        "gWDay": "So",
                        "gTime": "12:50",
                        "gGymnasiumID": "931",
                        "gGymnasiumNo": "23037",
                        "gGymnasiumName": "Werner-Stegmaier-Halle",
                        "gGymnasiumPostal": "76227",
                        "gGymnasiumTown": "Karlsruhe-Durlach",
                        "gGymnasiumStreet": "Untere Hub 1",
                        "gHomeTeam": "TS Durlach",
                        "gGuestTeam": "SG Hei/Hel/Gon",
                        "gHomeGoals": " ",
                        "gGuestGoals": " ",
                        "gHomeGoals_1": " ",
                        "gGuestGoals_1": " ",
                        "gHomePoints": " ",
                        "gGuestPoints": " ",
                        "gComment": " ",
                        "gGroupsortTxt": " ",
                        "gReferee": " "
                    },
                    {
                        "gID": "3979071",
                        "sGID": 0,
                        "gNo": "213042",
                        "live": false,
                        "gToken": "",
                        "gAppid": "",
                        "gDate": "06.12.20",
                        "gWDay": "So",
                        "gTime": "14:20",
                        "gGymnasiumID": "879",
                        "gGymnasiumNo": "22023",
                        "gGymnasiumName": "Jahnhalle",
                        "gGymnasiumPostal": "69221",
                        "gGymnasiumTown": "Dossenheim",
                        "gGymnasiumStreet": "Gerhart-Hauptmann-Straße 16",
                        "gHomeTeam": "TSG Dossenheim",
                        "gGuestTeam": "TSV Rintheim",
                        "gHomeGoals": " ",
                        "gGuestGoals": " ",
                        "gHomeGoals_1": " ",
                        "gGuestGoals_1": " ",
                        "gHomePoints": " ",
                        "gGuestPoints": " ",
                        "gComment": " ",
                        "gGroupsortTxt": " ",
                        "gReferee": " "
                    },
                    {
                        "gID": "3979066",
                        "sGID": 0,
                        "gNo": "213041",
                        "live": false,
                        "gToken": "",
                        "gAppid": "",
                        "gDate": "06.12.20",
                        "gWDay": "So",
                        "gTime": "18:00",
                        "gGymnasiumID": "821",
                        "gGymnasiumNo": "24034",
                        "gGymnasiumName": "Karl-Frei-Sporthalle",
                        "gGymnasiumPostal": "68723",
                        "gGymnasiumTown": "Oftersheim",
                        "gGymnasiumStreet": "Hardtwaldring 16",
                        "gHomeTeam": "HG Ofter/Schw 2",
                        "gGuestTeam": "JSG Rot-Malsch",
                        "gHomeGoals": " ",
                        "gGuestGoals": " ",
                        "gHomeGoals_1": " ",
                        "gGuestGoals_1": " ",
                        "gHomePoints": " ",
                        "gGuestPoints": " ",
                        "gComment": " ",
                        "gGroupsortTxt": " ",
                        "gReferee": " "
                    }
                ]
            },
            {
                "gClassID": "57826",
                "gClassSname": "mJB-BL",
                "gClassLname": "Badenliga männl. B",
                "gClassGender": "m",
                "gClassAGsDesc": "B",
                "gClassAGsYear": "15",
                "gRefAllocType": "org_of_responsible",
                "gRefRespOrg": "0",
                "games": [
                    {
                        "gID": "3953861",
                        "sGID": 0,
                        "gNo": "213352",
                        "live": false,
                        "gToken": "",
                        "gAppid": "",
                        "gDate": "05.12.20",
                        "gWDay": "Sa",
                        "gTime": "16:00",
                        "gGymnasiumID": "2273",
                        "gGymnasiumNo": "25018",
                        "gGymnasiumName": "Bertha-Benz-Halle",
                        "gGymnasiumPostal": "75172",
                        "gGymnasiumTown": "Pforzheim",
                        "gGymnasiumStreet": "Kiehnlestraße 25",
                        "gHomeTeam": "TGS Pforzheim",
                        "gGuestTeam": "JSG Rot-Malsch",
                        "gHomeGoals": " ",
                        "gGuestGoals": " ",
                        "gHomeGoals_1": " ",
                        "gGuestGoals_1": " ",
                        "gHomePoints": " ",
                        "gGuestPoints": " ",
                        "gComment": " ",
                        "gGroupsortTxt": " ",
                        "gReferee": " "
                    },
                    {
                        "gID": "3953871",
                        "sGID": 0,
                        "gNo": "213354",
                        "live": false,
                        "gToken": "",
                        "gAppid": "",
                        "gDate": "05.12.20",
                        "gWDay": "Sa",
                        "gTime": "16:15",
                        "gGymnasiumID": "485",
                        "gGymnasiumNo": "24010",
                        "gGymnasiumName": "Heinrich-Beck-Halle",
                        "gGymnasiumPostal": "69493",
                        "gGymnasiumTown": "Hirschberg-Leutershausen",
                        "gGymnasiumStreet": "Hölderlinstraße 24",
                        "gHomeTeam": "SG Leutersh.",
                        "gGuestTeam": "HSG Walzbacht.",
                        "gHomeGoals": " ",
                        "gGuestGoals": " ",
                        "gHomeGoals_1": " ",
                        "gGuestGoals_1": " ",
                        "gHomePoints": " ",
                        "gGuestPoints": " ",
                        "gComment": " ",
                        "gGroupsortTxt": " ",
                        "gReferee": " "
                    },
                    {
                        "gID": "3953856",
                        "sGID": 0,
                        "gNo": "213351",
                        "live": false,
                        "gToken": "",
                        "gAppid": "",
                        "gDate": "05.12.20",
                        "gWDay": "Sa",
                        "gTime": "18:00",
                        "gGymnasiumID": "818",
                        "gGymnasiumNo": "22021",
                        "gGymnasiumName": "Olympiahalle",
                        "gGymnasiumPostal": "69226",
                        "gGymnasiumTown": "Nußloch",
                        "gGymnasiumStreet": "Kurpfalzstraße 75",
                        "gHomeTeam": "SG Nußloch",
                        "gGuestTeam": "SG PF/Eutingen 2",
                        "gHomeGoals": " ",
                        "gGuestGoals": " ",
                        "gHomeGoals_1": " ",
                        "gGuestGoals_1": " ",
                        "gHomePoints": " ",
                        "gGuestPoints": " ",
                        "gComment": " ",
                        "gGroupsortTxt": " ",
                        "gReferee": " "
                    },
                    {
                        "gID": "3953866",
                        "sGID": 0,
                        "gNo": "213353",
                        "live": false,
                        "gToken": "",
                        "gAppid": "",
                        "gDate": "06.12.20",
                        "gWDay": "So",
                        "gTime": "11:15",
                        "gGymnasiumID": "931",
                        "gGymnasiumNo": "23037",
                        "gGymnasiumName": "Werner-Stegmaier-Halle",
                        "gGymnasiumPostal": "76227",
                        "gGymnasiumTown": "Karlsruhe-Durlach",
                        "gGymnasiumStreet": "Untere Hub 1",
                        "gHomeTeam": "TS Durlach",
                        "gGuestTeam": "TSV Rintheim",
                        "gHomeGoals": " ",
                        "gGuestGoals": " ",
                        "gHomeGoals_1": " ",
                        "gGuestGoals_1": " ",
                        "gHomePoints": " ",
                        "gGuestPoints": " ",
                        "gComment": " ",
                        "gGroupsortTxt": " ",
                        "gReferee": " "
                    },
                    {
                        "gID": "3953851",
                        "sGID": 0,
                        "gNo": "213350",
                        "live": false,
                        "gToken": "",
                        "gAppid": "",
                        "gDate": "06.12.20",
                        "gWDay": "So",
                        "gTime": "12:15",
                        "gGymnasiumID": "911",
                        "gGymnasiumNo": "23015",
                        "gGymnasiumName": "Sporthalle 1 Schulzentrum Blankenloch",
                        "gGymnasiumPostal": "76297",
                        "gGymnasiumTown": "Stutensee-Blankenloch",
                        "gGymnasiumStreet": "Gymnasiumstraße 20",
                        "gHomeTeam": "SG Stuten-Wein",
                        "gGuestTeam": "SG Eding/Fried",
                        "gHomeGoals": " ",
                        "gGuestGoals": " ",
                        "gHomeGoals_1": " ",
                        "gGuestGoals_1": " ",
                        "gHomePoints": " ",
                        "gGuestPoints": " ",
                        "gComment": " ",
                        "gGroupsortTxt": " ",
                        "gReferee": " "
                    },
                    {
                        "gID": "3953846",
                        "sGID": 0,
                        "gNo": "213349",
                        "live": false,
                        "gToken": "",
                        "gAppid": "",
                        "gDate": "06.12.20",
                        "gWDay": "So",
                        "gTime": "14:00",
                        "gGymnasiumID": "821",
                        "gGymnasiumNo": "24034",
                        "gGymnasiumName": "Karl-Frei-Sporthalle",
                        "gGymnasiumPostal": "68723",
                        "gGymnasiumTown": "Oftersheim",
                        "gGymnasiumStreet": "Hardtwaldring 16",
                        "gHomeTeam": "HG Ofter/Schw 2",
                        "gGuestTeam": "R-N Löwen 2",
                        "gHomeGoals": " ",
                        "gGuestGoals": " ",
                        "gHomeGoals_1": " ",
                        "gGuestGoals_1": " ",
                        "gHomePoints": " ",
                        "gGuestPoints": " ",
                        "gComment": " ",
                        "gGroupsortTxt": " ",
                        "gReferee": " "
                    }
                ]
            },
            {
                "gClassID": "57831",
                "gClassSname": "mJC-BL",
                "gClassLname": "Badenliga männl. C",
                "gClassGender": "m",
                "gClassAGsDesc": "C",
                "gClassAGsYear": "13",
                "gRefAllocType": "org_of_responsible",
                "gRefRespOrg": "0",
                "games": [
                    {
                        "gID": "3954481",
                        "sGID": 0,
                        "gNo": "213644",
                        "live": false,
                        "gToken": "",
                        "gAppid": "",
                        "gDate": "05.12.20",
                        "gWDay": "Sa",
                        "gTime": "13:45",
                        "gGymnasiumID": "487",
                        "gGymnasiumNo": "22010",
                        "gGymnasiumName": "Rebland-Halle",
                        "gGymnasiumPostal": "69254",
                        "gGymnasiumTown": "Malsch",
                        "gGymnasiumStreet": "Unterer Jagdweg 69",
                        "gHomeTeam": "JSG Rot-Malsch",
                        "gGuestTeam": "TSV Rintheim",
                        "gHomeGoals": " ",
                        "gGuestGoals": " ",
                        "gHomeGoals_1": " ",
                        "gGuestGoals_1": " ",
                        "gHomePoints": " ",
                        "gGuestPoints": " ",
                        "gComment": " ",
                        "gGroupsortTxt": " ",
                        "gReferee": " "
                    },
                    {
                        "gID": "3954486",
                        "sGID": 0,
                        "gNo": "213645",
                        "live": false,
                        "gToken": "",
                        "gAppid": "",
                        "gDate": "05.12.20",
                        "gWDay": "Sa",
                        "gTime": "14:30",
                        "gGymnasiumID": "496",
                        "gGymnasiumNo": "25008",
                        "gGymnasiumName": "Konrad-Adenauer-Sporthalle",
                        "gGymnasiumPostal": "75181",
                        "gGymnasiumTown": "Pforzheim",
                        "gGymnasiumStreet": "Kaulbachstraße 32",
                        "gHomeTeam": "SG PF/Eutingen",
                        "gGuestTeam": "TV Forst",
                        "gHomeGoals": " ",
                        "gGuestGoals": " ",
                        "gHomeGoals_1": " ",
                        "gGuestGoals_1": " ",
                        "gHomePoints": " ",
                        "gGuestPoints": " ",
                        "gComment": " ",
                        "gGroupsortTxt": " ",
                        "gReferee": " "
                    },
                    {
                        "gID": "3954476",
                        "sGID": 0,
                        "gNo": "213643",
                        "live": false,
                        "gToken": "",
                        "gAppid": "",
                        "gDate": "05.12.20",
                        "gWDay": "Sa",
                        "gTime": "16:45",
                        "gGymnasiumID": "597",
                        "gGymnasiumNo": "24005",
                        "gGymnasiumName": "Großsporthalle",
                        "gGymnasiumPostal": "68535",
                        "gGymnasiumTown": "Edingen-Neckarhausen",
                        "gGymnasiumStreet": "Robert-Walter-Straße 1",
                        "gHomeTeam": "SG Eding/Fried",
                        "gGuestTeam": "SG Leutersh.",
                        "gHomeGoals": " ",
                        "gGuestGoals": " ",
                        "gHomeGoals_1": " ",
                        "gGuestGoals_1": " ",
                        "gHomePoints": " ",
                        "gGuestPoints": " ",
                        "gComment": " ",
                        "gGroupsortTxt": " ",
                        "gReferee": " "
                    },
                    {
                        "gID": "3954471",
                        "sGID": 0,
                        "gNo": "213642",
                        "live": false,
                        "gToken": "",
                        "gAppid": "",
                        "gDate": "06.12.20",
                        "gWDay": "So",
                        "gTime": "11:20",
                        "gGymnasiumID": "879",
                        "gGymnasiumNo": "22023",
                        "gGymnasiumName": "Jahnhalle",
                        "gGymnasiumPostal": "69221",
                        "gGymnasiumTown": "Dossenheim",
                        "gGymnasiumStreet": "Gerhart-Hauptmann-Straße 16",
                        "gHomeTeam": "TSG Dossenheim",
                        "gGuestTeam": "R-N Löwen",
                        "gHomeGoals": " ",
                        "gGuestGoals": " ",
                        "gHomeGoals_1": " ",
                        "gGuestGoals_1": " ",
                        "gHomePoints": " ",
                        "gGuestPoints": " ",
                        "gComment": " ",
                        "gGroupsortTxt": " ",
                        "gReferee": " "
                    },
                    {
                        "gID": "3954466",
                        "sGID": 0,
                        "gNo": "213641",
                        "live": false,
                        "gToken": "",
                        "gAppid": "",
                        "gDate": "06.12.20",
                        "gWDay": "So",
                        "gTime": "12:30",
                        "gGymnasiumID": "821",
                        "gGymnasiumNo": "24034",
                        "gGymnasiumName": "Karl-Frei-Sporthalle",
                        "gGymnasiumPostal": "68723",
                        "gGymnasiumTown": "Oftersheim",
                        "gGymnasiumStreet": "Hardtwaldring 16",
                        "gHomeTeam": "HG Ofter/Schw",
                        "gGuestTeam": "ASG StL/Rei/Ho",
                        "gHomeGoals": " ",
                        "gGuestGoals": " ",
                        "gHomeGoals_1": " ",
                        "gGuestGoals_1": " ",
                        "gHomePoints": " ",
                        "gGuestPoints": " ",
                        "gComment": " ",
                        "gGroupsortTxt": " ",
                        "gReferee": " "
                    }
                ]
            },
            {
                "gClassID": "57836",
                "gClassSname": "wJA-BL",
                "gClassLname": "Badenliga weibl. A",
                "gClassGender": "w",
                "gClassAGsDesc": "A",
                "gClassAGsYear": "17",
                "gRefAllocType": "org_of_responsible",
                "gRefRespOrg": "0",
                "games": [
                    {
                        "gID": "3954916",
                        "sGID": 0,
                        "gNo": "213941",
                        "live": false,
                        "gToken": "",
                        "gAppid": "",
                        "gDate": "05.12.20",
                        "gWDay": "Sa",
                        "gTime": "16:00",
                        "gGymnasiumID": "901",
                        "gGymnasiumNo": "23005",
                        "gGymnasiumName": "Reinhold-Crocoll Sporthalle",
                        "gGymnasiumPostal": "76187",
                        "gGymnasiumTown": "Karlsruhe-Knielingen",
                        "gGymnasiumStreet": "Am Brurain 4-6",
                        "gHomeTeam": "SG KnEgg",
                        "gGuestTeam": "JSG Rot-Malsch",
                        "gHomeGoals": " ",
                        "gGuestGoals": " ",
                        "gHomeGoals_1": " ",
                        "gGuestGoals_1": " ",
                        "gHomePoints": " ",
                        "gGuestPoints": " ",
                        "gComment": " ",
                        "gGroupsortTxt": " ",
                        "gReferee": " "
                    },
                    {
                        "gID": "3954931",
                        "sGID": 0,
                        "gNo": "213944",
                        "live": false,
                        "gToken": "",
                        "gAppid": "",
                        "gDate": "05.12.20",
                        "gWDay": "Sa",
                        "gTime": "16:30",
                        "gGymnasiumID": "821",
                        "gGymnasiumNo": "24034",
                        "gGymnasiumName": "Karl-Frei-Sporthalle",
                        "gGymnasiumPostal": "68723",
                        "gGymnasiumTown": "Oftersheim",
                        "gGymnasiumStreet": "Hardtwaldring 16",
                        "gHomeTeam": "HG Ofter/Schw",
                        "gGuestTeam": "WSG Krai-Hardt",
                        "gHomeGoals": " ",
                        "gGuestGoals": " ",
                        "gHomeGoals_1": " ",
                        "gGuestGoals_1": " ",
                        "gHomePoints": " ",
                        "gGuestPoints": " ",
                        "gComment": " ",
                        "gGroupsortTxt": " ",
                        "gReferee": " "
                    },
                    {
                        "gID": "3954936",
                        "sGID": 0,
                        "gNo": "213945",
                        "live": false,
                        "gToken": "",
                        "gAppid": "",
                        "gDate": "06.12.20",
                        "gWDay": "So",
                        "gTime": "12:45",
                        "gGymnasiumID": "954",
                        "gGymnasiumNo": "24036",
                        "gGymnasiumName": "Fritz-Mannherz-Halle",
                        "gGymnasiumPostal": "68799",
                        "gGymnasiumTown": "Reilingen",
                        "gGymnasiumStreet": "Wilhelmstraße 42",
                        "gHomeTeam": "ASG Wie/StL/Re",
                        "gGuestTeam": "TV Schriesheim",
                        "gHomeGoals": " ",
                        "gGuestGoals": " ",
                        "gHomeGoals_1": " ",
                        "gGuestGoals_1": " ",
                        "gHomePoints": " ",
                        "gGuestPoints": " ",
                        "gComment": " ",
                        "gGroupsortTxt": " ",
                        "gReferee": " "
                    },
                    {
                        "gID": "3954921",
                        "sGID": 0,
                        "gNo": "213942",
                        "live": false,
                        "gToken": "",
                        "gAppid": "",
                        "gDate": "06.12.20",
                        "gWDay": "So",
                        "gTime": "13:00",
                        "gGymnasiumID": "484",
                        "gGymnasiumNo": "24002",
                        "gGymnasiumName": "Langenberg-Sporthalle",
                        "gGymnasiumPostal": "69488",
                        "gGymnasiumTown": "Birkenau",
                        "gGymnasiumStreet": "Bergstraße 17",
                        "gHomeTeam": "TSV Birkenau",
                        "gGuestTeam": "MSG HeLeuSaase",
                        "gHomeGoals": " ",
                        "gGuestGoals": " ",
                        "gHomeGoals_1": " ",
                        "gGuestGoals_1": " ",
                        "gHomePoints": " ",
                        "gGuestPoints": " ",
                        "gComment": " ",
                        "gGroupsortTxt": " ",
                        "gReferee": " "
                    },
                    {
                        "gID": "3954926",
                        "sGID": 0,
                        "gNo": "213943",
                        "live": false,
                        "gToken": "",
                        "gAppid": "",
                        "gDate": "06.12.20",
                        "gWDay": "So",
                        "gTime": "14:00",
                        "gGymnasiumID": "911",
                        "gGymnasiumNo": "23015",
                        "gGymnasiumName": "Sporthalle 1 Schulzentrum Blankenloch",
                        "gGymnasiumPostal": "76297",
                        "gGymnasiumTown": "Stutensee-Blankenloch",
                        "gGymnasiumStreet": "Gymnasiumstraße 20",
                        "gHomeTeam": "SG Stuten-Wein",
                        "gGuestTeam": "TV Bammental",
                        "gHomeGoals": " ",
                        "gGuestGoals": " ",
                        "gHomeGoals_1": " ",
                        "gGuestGoals_1": " ",
                        "gHomePoints": " ",
                        "gGuestPoints": " ",
                        "gComment": " ",
                        "gGroupsortTxt": " ",
                        "gReferee": " "
                    }
                ]
            },
            {
                "gClassID": "57841",
                "gClassSname": "wJB-BL",
                "gClassLname": "Badenliga weibl. B",
                "gClassGender": "w",
                "gClassAGsDesc": "B",
                "gClassAGsYear": "15",
                "gRefAllocType": "org_of_responsible",
                "gRefRespOrg": "0",
                "games": [
                    {
                        "gID": "3955386",
                        "sGID": 0,
                        "gNo": "214045",
                        "live": false,
                        "gToken": "",
                        "gAppid": "",
                        "gDate": "05.12.20",
                        "gWDay": "Sa",
                        "gTime": "14:45",
                        "gGymnasiumID": "961",
                        "gGymnasiumNo": "24045",
                        "gGymnasiumName": "TSG Halle am Hallenbad",
                        "gGymnasiumPostal": "69469",
                        "gGymnasiumTown": "Weinheim",
                        "gGymnasiumStreet": "Mannheimer Straße 11",
                        "gHomeTeam": "HSG Wein/Oberf",
                        "gGuestTeam": "TV Sinsheim",
                        "gHomeGoals": " ",
                        "gGuestGoals": " ",
                        "gHomeGoals_1": " ",
                        "gGuestGoals_1": " ",
                        "gHomePoints": " ",
                        "gGuestPoints": " ",
                        "gComment": " ",
                        "gGroupsortTxt": " ",
                        "gReferee": " "
                    },
                    {
                        "gID": "3955381",
                        "sGID": 0,
                        "gNo": "214044",
                        "live": false,
                        "gToken": "",
                        "gAppid": "",
                        "gDate": "05.12.20",
                        "gWDay": "Sa",
                        "gTime": "20:00",
                        "gGymnasiumID": "904",
                        "gGymnasiumNo": "23008",
                        "gGymnasiumName": "Sporthalle Rintheim",
                        "gGymnasiumPostal": "76131",
                        "gGymnasiumTown": "Karlsruhe-Rintheim",
                        "gGymnasiumStreet": "Mannheimer Straße 2",
                        "gHomeTeam": "TSV Rintheim",
                        "gGuestTeam": "TSV Birkenau",
                        "gHomeGoals": " ",
                        "gGuestGoals": " ",
                        "gHomeGoals_1": " ",
                        "gGuestGoals_1": " ",
                        "gHomePoints": " ",
                        "gGuestPoints": " ",
                        "gComment": "Zeit!!!",
                        "gGroupsortTxt": " ",
                        "gReferee": " "
                    },
                    {
                        "gID": "3955366",
                        "sGID": 0,
                        "gNo": "214041",
                        "live": false,
                        "gToken": "",
                        "gAppid": "",
                        "gDate": "06.12.20",
                        "gWDay": "So",
                        "gTime": "15:30",
                        "gGymnasiumID": "913",
                        "gGymnasiumNo": "23017",
                        "gGymnasiumName": "Sportzentrum Eggenstein 1",
                        "gGymnasiumPostal": "76344",
                        "gGymnasiumTown": "Eggenstein-Leopoldshafen",
                        "gGymnasiumStreet": "Buchheimer Weg 6",
                        "gHomeTeam": "TG Eggenstein",
                        "gGuestTeam": "R-N Löwen",
                        "gHomeGoals": " ",
                        "gGuestGoals": " ",
                        "gHomeGoals_1": " ",
                        "gGuestGoals_1": " ",
                        "gHomePoints": " ",
                        "gGuestPoints": " ",
                        "gComment": " ",
                        "gGroupsortTxt": " ",
                        "gReferee": " "
                    },
                    {
                        "gID": "3955376",
                        "sGID": 0,
                        "gNo": "214043",
                        "live": false,
                        "gToken": "",
                        "gAppid": "",
                        "gDate": "06.12.20",
                        "gWDay": "So",
                        "gTime": "16:20",
                        "gGymnasiumID": "933",
                        "gGymnasiumNo": "23039",
                        "gGymnasiumName": "Sporthalle",
                        "gGymnasiumPostal": "75045",
                        "gGymnasiumTown": "Walzbachtal-Wössingen",
                        "gGymnasiumStreet": "Wössinger Straße 123",
                        "gHomeTeam": "HSG Walzbacht.",
                        "gGuestTeam": "TB Pforzheim",
                        "gHomeGoals": " ",
                        "gGuestGoals": " ",
                        "gHomeGoals_1": " ",
                        "gGuestGoals_1": " ",
                        "gHomePoints": " ",
                        "gGuestPoints": " ",
                        "gComment": " ",
                        "gGroupsortTxt": " ",
                        "gReferee": " "
                    },
                    {
                        "gID": "3955371",
                        "sGID": 0,
                        "gNo": "214042",
                        "live": false,
                        "gToken": "",
                        "gAppid": "",
                        "gDate": "06.12.20",
                        "gWDay": "So",
                        "gTime": "17:30",
                        "gGymnasiumID": "866",
                        "gGymnasiumNo": "22005",
                        "gGymnasiumName": "Astoriahalle Sport u.Kultur Walldorf",
                        "gGymnasiumPostal": "69190",
                        "gGymnasiumTown": "Walldorf",
                        "gGymnasiumStreet": "Schwetzinger Straße 91",
                        "gHomeTeam": "ASG Walld/Wies",
                        "gGuestTeam": "TV Bammental",
                        "gHomeGoals": " ",
                        "gGuestGoals": " ",
                        "gHomeGoals_1": " ",
                        "gGuestGoals_1": " ",
                        "gHomePoints": " ",
                        "gGuestPoints": " ",
                        "gComment": " ",
                        "gGroupsortTxt": " ",
                        "gReferee": " "
                    }
                ]
            },
            {
                "gClassID": "57846",
                "gClassSname": "wJC-BL",
                "gClassLname": "Badenliga weibl. C",
                "gClassGender": "w",
                "gClassAGsDesc": "C",
                "gClassAGsYear": "13",
                "gRefAllocType": "org_of_responsible",
                "gRefRespOrg": "0",
                "games": [
                    {
                        "gID": "3955881",
                        "sGID": 0,
                        "gNo": "214154",
                        "live": false,
                        "gToken": "",
                        "gAppid": "",
                        "gDate": "05.12.20",
                        "gWDay": "Sa",
                        "gTime": "16:00",
                        "gGymnasiumID": "484",
                        "gGymnasiumNo": "24002",
                        "gGymnasiumName": "Langenberg-Sporthalle",
                        "gGymnasiumPostal": "69488",
                        "gGymnasiumTown": "Birkenau",
                        "gGymnasiumStreet": "Bergstraße 17",
                        "gHomeTeam": "TSV Birkenau",
                        "gGuestTeam": "TB Pforzheim",
                        "gHomeGoals": " ",
                        "gGuestGoals": " ",
                        "gHomeGoals_1": " ",
                        "gGuestGoals_1": " ",
                        "gHomePoints": " ",
                        "gGuestPoints": " ",
                        "gComment": " ",
                        "gGroupsortTxt": " ",
                        "gReferee": " "
                    },
                    {
                        "gID": "3955856",
                        "sGID": 0,
                        "gNo": "214149",
                        "live": false,
                        "gToken": "",
                        "gAppid": "",
                        "gDate": "05.12.20",
                        "gWDay": "Sa",
                        "gTime": "16:15",
                        "gGymnasiumID": "818",
                        "gGymnasiumNo": "22021",
                        "gGymnasiumName": "Olympiahalle",
                        "gGymnasiumPostal": "69226",
                        "gGymnasiumTown": "Nußloch",
                        "gGymnasiumStreet": "Kurpfalzstraße 75",
                        "gHomeTeam": "SG Nußloch",
                        "gGuestTeam": "JSG Neuth/Büch",
                        "gHomeGoals": " ",
                        "gGuestGoals": " ",
                        "gHomeGoals_1": " ",
                        "gGuestGoals_1": " ",
                        "gHomePoints": " ",
                        "gGuestPoints": " ",
                        "gComment": " ",
                        "gGroupsortTxt": " ",
                        "gReferee": " "
                    },
                    {
                        "gID": "3955866",
                        "sGID": 0,
                        "gNo": "214151",
                        "live": false,
                        "gToken": "",
                        "gAppid": "",
                        "gDate": "06.12.20",
                        "gWDay": "So",
                        "gTime": "12:00",
                        "gGymnasiumID": "537",
                        "gGymnasiumNo": "24014",
                        "gGymnasiumName": "Neurotthalle",
                        "gGymnasiumPostal": "68775",
                        "gGymnasiumTown": "Ketsch",
                        "gGymnasiumStreet": "Mannheimer Straße 27",
                        "gHomeTeam": "TSG Ketsch",
                        "gGuestTeam": "TV Sinsheim",
                        "gHomeGoals": " ",
                        "gGuestGoals": " ",
                        "gHomeGoals_1": " ",
                        "gGuestGoals_1": " ",
                        "gHomePoints": " ",
                        "gGuestPoints": " ",
                        "gComment": " ",
                        "gGroupsortTxt": " ",
                        "gReferee": " "
                    },
                    {
                        "gID": "3955871",
                        "sGID": 0,
                        "gNo": "214152",
                        "live": false,
                        "gToken": "",
                        "gAppid": "",
                        "gDate": "06.12.20",
                        "gWDay": "So",
                        "gTime": "12:00",
                        "gGymnasiumID": "488",
                        "gGymnasiumNo": "25006",
                        "gGymnasiumName": "Sporthalle beim Fritz-Erler-Gymnasium",
                        "gGymnasiumPostal": "75172",
                        "gGymnasiumTown": "Pforzheim",
                        "gGymnasiumStreet": "Westliche Karl-Friedrich-Straße 215",
                        "gHomeTeam": "TG Pforzheim",
                        "gGuestTeam": "TSV Rintheim",
                        "gHomeGoals": " ",
                        "gGuestGoals": " ",
                        "gHomeGoals_1": " ",
                        "gGuestGoals_1": " ",
                        "gHomePoints": " ",
                        "gGuestPoints": " ",
                        "gComment": " ",
                        "gGroupsortTxt": " ",
                        "gReferee": " "
                    },
                    {
                        "gID": "3955876",
                        "sGID": 0,
                        "gNo": "214153",
                        "live": false,
                        "gToken": "",
                        "gAppid": "",
                        "gDate": "06.12.20",
                        "gWDay": "So",
                        "gTime": "14:00",
                        "gGymnasiumID": "913",
                        "gGymnasiumNo": "23017",
                        "gGymnasiumName": "Sportzentrum Eggenstein 1",
                        "gGymnasiumPostal": "76344",
                        "gGymnasiumTown": "Eggenstein-Leopoldshafen",
                        "gGymnasiumStreet": "Buchheimer Weg 6",
                        "gHomeTeam": "TG Eggenstein",
                        "gGuestTeam": "R-N Löwen",
                        "gHomeGoals": " ",
                        "gGuestGoals": " ",
                        "gHomeGoals_1": " ",
                        "gGuestGoals_1": " ",
                        "gHomePoints": " ",
                        "gGuestPoints": " ",
                        "gComment": " ",
                        "gGroupsortTxt": " ",
                        "gReferee": " "
                    },
                    {
                        "gID": "3955861",
                        "sGID": 0,
                        "gNo": "214150",
                        "live": false,
                        "gToken": "",
                        "gAppid": "",
                        "gDate": "06.12.20",
                        "gWDay": "So",
                        "gTime": "14:40",
                        "gGymnasiumID": "933",
                        "gGymnasiumNo": "23039",
                        "gGymnasiumName": "Sporthalle",
                        "gGymnasiumPostal": "75045",
                        "gGymnasiumTown": "Walzbachtal-Wössingen",
                        "gGymnasiumStreet": "Wössinger Straße 123",
                        "gHomeTeam": "HSG Walzbacht.",
                        "gGuestTeam": "TV Bammental",
                        "gHomeGoals": " ",
                        "gGuestGoals": " ",
                        "gHomeGoals_1": " ",
                        "gGuestGoals_1": " ",
                        "gHomePoints": " ",
                        "gGuestPoints": " ",
                        "gComment": " ",
                        "gGroupsortTxt": " ",
                        "gReferee": " "
                    }
                ]
            }
        ]
    },
    "footer": [],
    "error": null,
    "debug": {
        "parseParams": {
            "debug": "( /  / )",
            "explanation": "(_GET / _POST / value)",
            "cmd": "(po /  / po)",
            "og": "(35 /  / 35)",
            "o": "(35 /  / 35)",
            "p": "( /  / )",
            "do": "( /  / )",
            "refprg": "( /  / )",
            "mdts": "( /  / )",
            "g": "( /  / )",
            "c": "( /  / )",
            "cl": "( /  / )",
            "ca": "( /  / )",
            "ct": "( /  / )",
            "nv": "( /  / )"
        }
    }
} as RawAssociation

class SuccessResolver implements Resolver<RawAssociation> {
    async resolve() : Promise<RawAssociation> {
        return ASSOCIATION
    }
}

function stringToInt(s: string): number {
    return parseInt(s, 10)
}

function isOrganisationIdHigher(baseId: string, compareId: string): boolean {
    const baseIdInt = stringToInt(baseId)
    const compareIdInt = stringToInt(compareId)

    return baseIdInt > compareIdInt
}

function getSubOrganisationIds(): Set<string> {
    const ids = Object.keys(ASSOCIATION.menu.org.list)
    const cleanIds = ids.filter((id) => isOrganisationIdHigher(id, ASSOCIATION.menu.org.selectedID) )

    return new Set(cleanIds)
}

function getSeasonIds(): Set<string> {
    const ids = Object.keys(ASSOCIATION.menu.period.list)

    return new Set(ids)
}

function getLeagueIds(): Set<string> {
    const ids = ASSOCIATION.content.classes.map(league => league.gClassID)

    return new Set(ids)
}

describe("Association transformer", () => {
    let rawAssociation: RawAssociation
    let association: Association

    beforeAll(async () => {
        const resolver = new SuccessResolver()

        rawAssociation = await resolver.resolve()
        association = transformRawAssociation(rawAssociation)
    })

    test("Id", async () => {
        expect(association.id).toBe(rawAssociation.menu.org.selectedID)
    })

    test("Name", async () => {
        expect(association.name).toBe(rawAssociation.head.name)
    })

    test("Short name", async () => {
        expect(association.shortName).toBe(rawAssociation.head.sname)
    })
    
    test("Suborganisation Ids", async () => {
        const ids = getSubOrganisationIds()

        expect(association.subOrganisationIds).toStrictEqual(ids)
    })

    test("Season Ids", async () => {
        const ids = getSeasonIds()

        expect(association.seasonIds).toStrictEqual(ids)
    })

    test("League Ids", async () => {
        const ids = getLeagueIds()

        expect(association.leagueIds).toStrictEqual(ids)
    })
})
