service: league-generate
# app and org for use with dashboard.serverless.com
#app: your-app-name
#org: your-org-name

provider:
  name: aws
  runtime: nodejs10.x
  memorySize: 512
  timeout: 30

  region: eu-central-1

  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Scan
      Resource:
        Fn::Join:
          - ':'
          - - arn
            - aws
            - dynamodb
            - Ref: AWS::Region
            - Ref: AWS::AccountId
            - table/${file(../config.json):game-table-name}

    - Effect: Allow
      Action:
        - s3:PutObject
      Resource: arn:aws:s3:::${file(../config.json):bucket-name}/assets/*

  environment:
    BUCKET_NAME: ${file(../config.json):bucket-name}
    TABLE_NAME: ${file(../config.json):game-table-name}

functions:
  league-generate:
    handler: handler.generateLeague
    events:
      - sqs:
          arn:
            Fn::Join:
              - ':'
              - - arn
                - aws
                - sqs
                - Ref: AWS::Region
                - Ref: AWS::AccountId
                - ${file(../config.json):league-generate-queue-name}
          batchSize: 1
