name: CI

on:
  push:
    branches:
      - v2.0

jobs:
  build app:
    runs-on: ubuntu-latest

    container:
      image: node:14.15-buster

    steps:
    - uses: actions/checkout@v2

    - name: Install npm dependencies
      run: |
        npm ci

    - name: Build nx
      uses: mansagroup/nrwl-nx-action@v1
      with:
        targets: build
        all: true

  build cdk:
    runs-on: ubuntu-latest

    container:
      image: node:14.15-buster

    steps:
    - uses: actions/checkout@v2

    - name: Install npm dependencies
      run: |
        (cd cdk && npm ci)

    - name: Build cdk
      run: |
        (cd cdk && npm run build)

  deploy:
    runs-on: ubuntu-latest

    needs: 
    - build app
    - build cdk

    steps:
    - uses: actions/checkout@v2

    - uses: youyo/aws-cdk-github-actions@v1
      with:
        cdk_subcommand: 'deploy'
        cdk_args: '--require-approval never'
        actions_comment: false
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: 'eu-central-1'

