name: CI

on:
  push:
    branches:
      - v2.0

jobs:
  build-app:
    runs-on: ubuntu-latest

    container:
      image: node:14.15-buster

    steps:
    - uses: actions/checkout@v2

    - name: Install nx
      run: |
        npm install -g nx@10.4.4

    - name: Install package dependencies
      run: |
        npm ci

    - name: Build nx
      run: |
        nx affected:build --all

  build-cdk:
    runs-on: ubuntu-latest

    container:
      image: node:14.15-buster

    steps:
    - uses: actions/checkout@v2

    - name: Install npm dependencies
      run: |
        (cd cdk && npm ci)

    - name: Build cdk
      run: |
        (cd cdk && npm run build)

  deploy:
    runs-on: ubuntu-latest

    container:
      image: node:14.15-buster

    needs: 
    - build-app
    - build-cdk

    steps:
    - uses: actions/checkout@v2

    - name: Install cdk@1.80.0
      run: |
        (cd cdk && cdk deploy)
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: 'eu-central-1'

