name: Node CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
      run: |
        npm install -g serverless:1.55.1
    - name: Build
      run: |
        ci/install.sh
        ci/deploy.sh
      env:
        CI: true
